### ISSUE TITLE
AttributeError: 'SitemapGenerator' object has no attribute 'settings'

### ISSUE THREAD

**Issue by rwev** [MaevaBrunelles/ave_seo#5]
Hi! Thanks for the plugin, although I haven't gotten it to work yet. 
I'm getting the following error: 
```
CRITICAL: AttributeError: 'SitemapGenerator' object has no attribute 'settings'
Traceback (most recent call last):
  File "//pelican-plugins/ave_seo/ave_seo.py", line 33, in run_seo_report_robots_file
    if not generator.settings.get('SITEURL'):
AttributeError: 'SitemapGenerator' object has no attribute 'settings'
```
`SITEURL` is defined in my `pelicanconf.py`. Perhaps this is a versioning issue? I'm running Python 3.6.8 and the latest Pelican. 

Thanks!

**Comment by MaevaBrunelles** [comment]
Hello @rwev,

I've to apologize, I just saw your message... I'm currently working again on my plugin in order to make it available directly through https://github.com/getpelican/pelican-plugins 

If you still need help on this issue, it seems there is a conflict between my plugin and `sitemap` plugin. I guess you're using it because `SitemapGenerator` is not an object of mine. Can you confirm it? 

Thanks for your feedback

**Comment by MaevaBrunelles** [comment]
Hello @rwev,

I was right, this issue came from a conflict between `sitemap` plugin and `ave_seo`. I succeed to reproduce the bug, and I fixed it here: https://github.com/MaevaBrunelles/ave_seo/commit/9a8c7b2f65fcac57719f70d62e039fde9ec7a9a2 
I got the settings from `generators`, but `sitemap` generate a `SitemapGenerator`, and my code tried to access to `SitemapGenerator.settings`, which doesn't exist. I reduced the perimeter of this access only to Pelican Generator and it now works.

If you still want to use this plugin, don't hesitate to try the fix and put a feedback here, I'll be more reactive this time :)
